### ISSUE TITLE
is this thread safe?

### ISSUE THREAD

**Issue by tmc** [WeAreFarmGeek/tld_length#1]

**Comment by johnhamelink** [comment]
@tmc thanks for checking out this project! As you can see by the git log history, I've not updated this since October 2014 - I don't code in ruby day to day anymore (I use Elixir these days). If this gem still works, then great! But I am not planning on  updating it any time soon.

So to answer your question: I don't know if it is thread safe (or even functional in rails >= 5.x), and I don't plan on spending the time to investigate.

As usual, PRs are very welcome!

**Comment by javiercr** [comment]
Just for whoever may find this issue in the future:

We were using this gem successfully with Unicorn, then switched to Puma and found (the hard way) that this middleware is not thread safe. Here is some more context:
https://stackoverflow.com/questions/62899816/how-to-set-tld-length-dynamically-on-a-rails-app-with-puma-thread-safe

Thank you anyways to the authors of the gem for sharing it with everyone.
